// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(BookRentalDbContext))]
    [Migration("20211001191530_ReviewsAddedToBook")]
    partial class ReviewsAddedToBook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuthorBookTemplate", b =>
                {
                    b.Property<int>("AuthorsBooksId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsBooksId", "AuthorsId");

                    b.HasIndex("AuthorsId");

                    b.ToTable("AuthorBookTemplate");
                });

            modelBuilder.Entity("BookCollectionBookTemplate", b =>
                {
                    b.Property<int>("BookCollectionId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("BookCollectionId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("BookCollectionBookTemplate");
                });

            modelBuilder.Entity("BookTemplateGenre", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("GenresGenreID")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "GenresGenreID");

                    b.HasIndex("GenresGenreID");

                    b.ToTable("BookTemplateGenre");
                });

            modelBuilder.Entity("DAL.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Surname")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "William Shakespeare was an English playwright, poet, and actor, widely regarded as the greatest writer in the English language and the world's greatest dramatist.",
                            Name = "William",
                            Surname = "Shakespeare"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mary Wollstonecraft Shelley (30 August 1797 – 1 February 1851) was an English novelist who wrote the Gothic novel Frankenstein; or, The Modern Prometheus (1818), which is considered an early example of science fiction.",
                            Name = "Mary",
                            Surname = "Shelley"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Charlotte Brontë (21 April 1816 – 31 March 1855) was an English novelist and poet, the eldest of the three Brontë sisters who survived into adulthood and whose novels became classics of English literature.",
                            Name = "Charlotte",
                            Surname = "Brontë"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Emily Jane Brontë (30 July 1818 – 19 December 1848) was an English novelist and poet who is best known for her only novel, Wuthering Heights, now considered a classic of English literature.",
                            Name = "Emily",
                            Surname = "Brontë"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Jules Gabriel Verne (8 February 1828 – 24 March 1905) was a French novelist, poet, and playwright. His collaboration with the publisher Pierre-Jules Hetzel led to the creation of the Voyages extraordinaires, a series of bestselling adventure novels.",
                            Name = "Jules",
                            Surname = "Verne"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Jane Austen (16 December 1775 – 18 July 1817) was an English novelist known primarily for her six major novels, which interpret, critique and comment upon the British landed gentry at the end of the 18th century.",
                            Name = "Jane",
                            Surname = "Austen"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Charles John Huffam Dickens (7 February 1812 – 9 June 1870) was an English writer and social critic. He created some of the world's best-known fictional characters and is regarded by many as the greatest novelist of the Victorian era.",
                            Name = "Charles",
                            Surname = "Dickens"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Edgar Allan Poe (born Edgar Poe; January 19, 1809 – October 7, 1849) was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. ",
                            Name = "Edgar Allan",
                            Surname = "Poe"
                        });
                });

            modelBuilder.Entity("DAL.Entities.BookCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BookCollections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2021, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Just classics.",
                            Title = "Classics",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DAL.Entities.BookInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookTemplateID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookTemplateID");

                    b.ToTable("BookInstances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookTemplateID = 1
                        },
                        new
                        {
                            Id = 2,
                            BookTemplateID = 1
                        },
                        new
                        {
                            Id = 3,
                            BookTemplateID = 1
                        });
                });

            modelBuilder.Entity("DAL.Entities.BookTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfRelease")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("BookTemplates");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BookTemplate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfRelease = new DateTime(1818, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Victor Frankenstein, a brilliant but wayward scientist, builds a human from dead flesh. Horrified at what he has done, he abandons his creation. The hideous creature learns language and becomes civilized but society rejects him. Spurned, he seeks vengeance on his creator. So begins a cycle of destruction, with Frankenstein and his 'monster' pursuing each other to the extremes of nature until all vestiges of their humanity are lost.",
                            ISBN = "9781509827756",
                            Language = 0,
                            PageCount = 280,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            Id = 2,
                            DateOfRelease = new DateTime(1600, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Considered one of Shakespeare′s most rich and enduring plays, the depiction of its hero Hamlet as he vows to avenge the murder of his father by his brother Claudius is both powerful and complex. As Hamlet tries to find out the truth of the situation, his troubled relationship with his mother comes to the fore, as do the paradoxes in his personality. A play of carefully crafted conflict and tragedy, Shakespeare′s intricate dialogue continues to fascinate audiences to this day.",
                            ISBN = "9780007902347",
                            Language = 0,
                            PageCount = 192,
                            Title = "Hamlet"
                        },
                        new
                        {
                            Id = 3,
                            DateOfRelease = new DateTime(1591, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shakespeare's immortal drama tells the story of star-crossed lovers, rival dynasties and bloody revenge. Romeo and Juliet is a hymn to youth and the thrill of forbidden love, charged with sexual passion and violence, but also a warning of death: a dazzling combination of bawdy comedy and high tragedy.",
                            ISBN = "9780007902361",
                            Language = 0,
                            PageCount = 160,
                            Title = "Romeo and Juliet"
                        });
                });

            modelBuilder.Entity("DAL.Entities.EBookInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EBookTemplateID")
                        .HasColumnType("int");

                    b.Property<int>("EReaderID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EBookTemplateID");

                    b.HasIndex("EReaderID");

                    b.ToTable("EBookInstances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EBookTemplateID = 4,
                            EReaderID = 1
                        },
                        new
                        {
                            Id = 2,
                            EBookTemplateID = 4,
                            EReaderID = 1
                        });
                });

            modelBuilder.Entity("DAL.Entities.EReaderInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EReaderTemplateID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EReaderTemplateID");

                    b.ToTable("EReaderInstances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EReaderTemplateID = 1
                        },
                        new
                        {
                            Id = 2,
                            EReaderTemplateID = 1
                        },
                        new
                        {
                            Id = 3,
                            EReaderTemplateID = 2
                        });
                });

            modelBuilder.Entity("DAL.Entities.EReaderTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyMake")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("MemoryInMB")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("EReaderTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyMake = "PocketBook",
                            MemoryInMB = 16000,
                            Model = "632 Touch HD 3"
                        },
                        new
                        {
                            Id = 2,
                            CompanyMake = "ONYX BOOX",
                            MemoryInMB = 32000,
                            Model = "Nova 3"
                        },
                        new
                        {
                            Id = 3,
                            CompanyMake = "PocketBook",
                            MemoryInMB = 32000,
                            Model = "1040 InkPad X"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.HasKey("GenreID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreID = 2
                        },
                        new
                        {
                            GenreID = 4
                        });
                });

            modelBuilder.Entity("DAL.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BookInstanceID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("Date");

                    b.Property<DateTime>("DateTill")
                        .HasColumnType("Date");

                    b.Property<int?>("EReaderID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookInstanceID");

                    b.HasIndex("EReaderID");

                    b.HasIndex("UserID");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookInstanceID = 1,
                            DateFrom = new DateTime(2021, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            BookInstanceID = 2,
                            DateFrom = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 1
                        },
                        new
                        {
                            Id = 3,
                            BookInstanceID = 3,
                            DateFrom = new DateTime(2021, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 1
                        },
                        new
                        {
                            Id = 4,
                            BookInstanceID = 1,
                            DateFrom = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 2
                        },
                        new
                        {
                            Id = 5,
                            BookInstanceID = 2,
                            DateFrom = new DateTime(2021, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 2
                        });
                });

            modelBuilder.Entity("DAL.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookTemplateID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("Date");

                    b.Property<int>("StarsAmmount")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookTemplateID");

                    b.HasIndex("UserID");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookTemplateID = 1,
                            Content = "Best",
                            CreationDate = new DateTime(2021, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StarsAmmount = 5,
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            BookTemplateID = 1,
                            Content = "Great!!",
                            CreationDate = new DateTime(2021, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StarsAmmount = 5,
                            UserID = 1
                        },
                        new
                        {
                            Id = 3,
                            BookTemplateID = 1,
                            Content = "huh",
                            CreationDate = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StarsAmmount = 1,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HashedPassword")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Surname")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@gmail.com",
                            HashedPassword = "",
                            IsAdmin = true,
                            Name = "Alice",
                            Surname = "First"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@gmail.com",
                            HashedPassword = "",
                            IsAdmin = false,
                            Name = "Bob",
                            Surname = "Second"
                        },
                        new
                        {
                            Id = 3,
                            Email = "evee@gmail.com",
                            HashedPassword = "",
                            IsAdmin = false,
                            Name = "Eve",
                            Surname = "Third"
                        });
                });

            modelBuilder.Entity("DAL.Entities.EBookTemplate", b =>
                {
                    b.HasBaseType("DAL.Entities.BookTemplate");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<int>("MemorySize")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("EBookTemplate");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            DateOfRelease = new DateTime(1591, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shakespeare's immortal drama tells the story of star-crossed lovers, rival dynasties and bloody revenge. Romeo and Juliet is a hymn to youth and the thrill of forbidden love, charged with sexual passion and violence, but also a warning of death: a dazzling combination of bawdy comedy and high tragedy.",
                            ISBN = "9780141920252",
                            Language = 0,
                            PageCount = 320,
                            Title = "Romeo and Juliet",
                            Format = 0,
                            MemorySize = 1024
                        });
                });

            modelBuilder.Entity("AuthorBookTemplate", b =>
                {
                    b.HasOne("DAL.Entities.BookTemplate", null)
                        .WithMany()
                        .HasForeignKey("AuthorsBooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookCollectionBookTemplate", b =>
                {
                    b.HasOne("DAL.Entities.BookCollection", null)
                        .WithMany()
                        .HasForeignKey("BookCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.BookTemplate", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookTemplateGenre", b =>
                {
                    b.HasOne("DAL.Entities.BookTemplate", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresGenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.BookCollection", b =>
                {
                    b.HasOne("DAL.Entities.User", null)
                        .WithMany("BookCollections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.BookInstance", b =>
                {
                    b.HasOne("DAL.Entities.BookTemplate", "FromBookTemplate")
                        .WithMany("BookInstances")
                        .HasForeignKey("BookTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromBookTemplate");
                });

            modelBuilder.Entity("DAL.Entities.EBookInstance", b =>
                {
                    b.HasOne("DAL.Entities.EBookTemplate", "FromBookTemplate")
                        .WithMany("EBookInstances")
                        .HasForeignKey("EBookTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.EReaderInstance", "EReaderPlace")
                        .WithMany("BooksIncluded")
                        .HasForeignKey("EReaderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EReaderPlace");

                    b.Navigation("FromBookTemplate");
                });

            modelBuilder.Entity("DAL.Entities.EReaderInstance", b =>
                {
                    b.HasOne("DAL.Entities.EReaderTemplate", "EReaderTemplate")
                        .WithMany()
                        .HasForeignKey("EReaderTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EReaderTemplate");
                });

            modelBuilder.Entity("DAL.Entities.Reservation", b =>
                {
                    b.HasOne("DAL.Entities.BookInstance", "ReserveredBook")
                        .WithMany("AllReservations")
                        .HasForeignKey("BookInstanceID");

                    b.HasOne("DAL.Entities.EReaderInstance", "EReader")
                        .WithMany()
                        .HasForeignKey("EReaderID");

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EReader");

                    b.Navigation("ReserveredBook");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Review", b =>
                {
                    b.HasOne("DAL.Entities.BookTemplate", "ReserveredBook")
                        .WithMany("Reviews")
                        .HasForeignKey("BookTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReserveredBook");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.BookInstance", b =>
                {
                    b.Navigation("AllReservations");
                });

            modelBuilder.Entity("DAL.Entities.BookTemplate", b =>
                {
                    b.Navigation("BookInstances");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DAL.Entities.EReaderInstance", b =>
                {
                    b.Navigation("BooksIncluded");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Navigation("BookCollections");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DAL.Entities.EBookTemplate", b =>
                {
                    b.Navigation("EBookInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
