// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(BookRentalDbContext))]
    partial class BookRentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Surname")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "William Shakespeare was an English playwright, poet, and actor, widely regarded as the greatest writer in the English language and the world's greatest dramatist.",
                            Name = "William",
                            Surname = "Shakespeare"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mary Wollstonecraft Shelley (30 August 1797 – 1 February 1851) was an English novelist who wrote the Gothic novel Frankenstein; or, The Modern Prometheus (1818), which is considered an early example of science fiction.",
                            Name = "Mary",
                            Surname = "Shelley"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Charlotte Brontë (21 April 1816 – 31 March 1855) was an English novelist and poet, the eldest of the three Brontë sisters who survived into adulthood and whose novels became classics of English literature.",
                            Name = "Charlotte",
                            Surname = "Brontë"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Emily Jane Brontë (30 July 1818 – 19 December 1848) was an English novelist and poet who is best known for her only novel, Wuthering Heights, now considered a classic of English literature.",
                            Name = "Emily",
                            Surname = "Brontë"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Jules Gabriel Verne (8 February 1828 – 24 March 1905) was a French novelist, poet, and playwright. His collaboration with the publisher Pierre-Jules Hetzel led to the creation of the Voyages extraordinaires, a series of bestselling adventure novels.",
                            Name = "Jules",
                            Surname = "Verne"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Jane Austen (16 December 1775 – 18 July 1817) was an English novelist known primarily for her six major novels, which interpret, critique and comment upon the British landed gentry at the end of the 18th century.",
                            Name = "Jane",
                            Surname = "Austen"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Charles John Huffam Dickens (7 February 1812 – 9 June 1870) was an English writer and social critic. He created some of the world's best-known fictional characters and is regarded by many as the greatest novelist of the Victorian era.",
                            Name = "Charles",
                            Surname = "Dickens"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Edgar Allan Poe (born Edgar Poe; January 19, 1809 – October 7, 1849) was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. ",
                            Name = "Edgar Allan",
                            Surname = "Poe"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Douglas Noël Adams was an English author, comic radio dramatist, and musician. He is best known as the author of the Hitchhiker's Guide to the Galaxy series. Hitchhiker's began on radio, and developed into a trilogy of five books (which sold more than fifteen million copies during his lifetime) as well as a television series, a comic book series, a computer game, and a feature film that was completed after Adams' death. The series has also been adapted for live theatre using various scripts; the earliest such productions used material newly written by Adams. He was known to some fans as Bop Ad (after his illegible signature), or by his initials \"DNA\".",
                            Name = "Douglas",
                            Surname = "Adams"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Eric Arthur Blair, better known by his pen name George Orwell, was an English author and journalist. His work is marked by keen intelligence and wit, a profound awareness of social injustice, an intense opposition to totalitarianism, a passion for clarity in language, and a belief in democratic socialism.",
                            Name = "George",
                            Surname = "Orwell"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Dan Brown is the author of numerous #1 bestselling novels, including The Da Vinci Code, which has become one of the best selling novels of all time as well as the subject of intellectual debate among readers and scholars. Brown’s novels are published in 52 languages around the world with 200 million copies in print.",
                            Name = "Dan",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Antoine de Saint-Exupéry was born in Lyons on June 29, 1900. He flew for the first time at the age of twelve, at the Ambérieu airfield, and it was then that he became determined to be a pilot. He kept that ambition even after moving to a school in Switzerland and while spending summer vacations at the family's château at Saint-Maurice-de-Rémens, in eastern France. (The house at Saint-Maurice appears again and again in Saint-Exupéry's writing.)",
                            Name = "Antoine",
                            Surname = "de Saint-Exupéry"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfRelease")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfRelease = new DateTime(1818, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Victor Frankenstein, a brilliant but wayward scientist, builds a human from dead flesh. Horrified at what he has done, he abandons his creation. The hideous creature learns language and becomes civilized but society rejects him. Spurned, he seeks vengeance on his creator. So begins a cycle of destruction, with Frankenstein and his 'monster' pursuing each other to the extremes of nature until all vestiges of their humanity are lost.",
                            ISBN = "9781509827756",
                            Language = 0,
                            PageCount = 280,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            Id = 2,
                            DateOfRelease = new DateTime(1600, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Considered one of Shakespeare′s most rich and enduring plays, the depiction of its hero Hamlet as he vows to avenge the murder of his father by his brother Claudius is both powerful and complex. As Hamlet tries to find out the truth of the situation, his troubled relationship with his mother comes to the fore, as do the paradoxes in his personality. A play of carefully crafted conflict and tragedy, Shakespeare′s intricate dialogue continues to fascinate audiences to this day.",
                            ISBN = "9780007902347",
                            Language = 0,
                            PageCount = 192,
                            Title = "Hamlet"
                        },
                        new
                        {
                            Id = 3,
                            DateOfRelease = new DateTime(1591, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shakespeare's immortal drama tells the story of star-crossed lovers, rival dynasties and bloody revenge. Romeo and Juliet is a hymn to youth and the thrill of forbidden love, charged with sexual passion and violence, but also a warning of death: a dazzling combination of bawdy comedy and high tragedy.",
                            ISBN = "9780007902361",
                            Language = 0,
                            PageCount = 160,
                            Title = "Romeo and Juliet"
                        },
                        new
                        {
                            Id = 4,
                            DateOfRelease = new DateTime(2007, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shakespeare's immortal drama tells the story of star-crossed lovers, rival dynasties and bloody revenge. Romeo and Juliet is a hymn to youth and the thrill of forbidden love, charged with sexual passion and violence, but also a warning of death: a dazzling combination of bawdy comedy and high tragedy.",
                            ISBN = "9780671461492",
                            Language = 0,
                            PageCount = 193,
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = 5,
                            DateOfRelease = new DateTime(1943, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A pilot stranded in the desert awakes one morning to see, standing before him, the most extraordinary little fellow. \"Please,\" asks the stranger, \"draw me a sheep.\" And the pilot realizes that when life's events are too difficult to understand, there is no choice but to succumb to their mysteries. He pulls out pencil and paper... And thus begins this wise and enchanting fable that, in teaching the secret of what is really important in life, has changed forever the world for its readers.",
                            ISBN = "9783140464079",
                            Language = 0,
                            PageCount = 96,
                            Title = "The Little Prince"
                        },
                        new
                        {
                            Id = 6,
                            DateOfRelease = new DateTime(2006, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter.",
                            ISBN = "9780307277671 ",
                            Language = 0,
                            PageCount = 489,
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = 7,
                            DateOfRelease = new DateTime(1945, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned –a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible. When Animal Farm was first published, Stalinist Russia was seen as its target. Today it is devastatingly clear that wherever and whenever freedom is attacked,under whatever banner,the cutting clarity and savage comedy of George Orwell’s masterpiece have a meaning and message still ferociously fresh.",
                            ISBN = "9780451526342",
                            Language = 0,
                            PageCount = 141,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = 8,
                            DateOfRelease = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work \"her own darling child\" and its vivacious heroine, Elizabeth Bennet, \" as delightful a creature as ever appeared in print.\" The romantic clash between the opinionated Elizabeth and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring. And Jane Austen's radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue, making this book the most superb comedy of manners of Regency England.",
                            ISBN = "9780679783268",
                            Language = 0,
                            PageCount = 279,
                            Title = "Pride and Prejudice"
                        });
                });

            modelBuilder.Entity("DAL.Entities.BookCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BookCollections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2021, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Just classics.",
                            Title = "Classics",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DAL.Entities.BookInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("BookTemplateID")
                        .HasColumnType("int");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookOwnerId");

                    b.HasIndex("BookTemplateID");

                    b.ToTable("BookInstances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookOwnerId = 1,
                            BookTemplateID = 1,
                            Condition = 4
                        },
                        new
                        {
                            Id = 2,
                            BookOwnerId = 1,
                            BookTemplateID = 2,
                            Condition = 4
                        },
                        new
                        {
                            Id = 3,
                            BookOwnerId = 2,
                            BookTemplateID = 3,
                            Condition = 0
                        },
                        new
                        {
                            Id = 4,
                            BookOwnerId = 3,
                            BookTemplateID = 4,
                            Condition = 0
                        },
                        new
                        {
                            Id = 5,
                            BookOwnerId = 4,
                            BookTemplateID = 5,
                            Condition = 3
                        },
                        new
                        {
                            Id = 6,
                            BookOwnerId = 5,
                            BookTemplateID = 6,
                            Condition = 2
                        },
                        new
                        {
                            Id = 7,
                            BookOwnerId = 5,
                            BookTemplateID = 7,
                            Condition = 3
                        },
                        new
                        {
                            Id = 8,
                            BookOwnerId = 3,
                            BookTemplateID = 8,
                            Condition = 5
                        });
                });

            modelBuilder.Entity("DAL.Entities.ConnectionTables.AuthorBook", b =>
                {
                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.HasKey("BookID", "AuthorID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Author_Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            AuthorID = 2
                        },
                        new
                        {
                            BookID = 2,
                            AuthorID = 1
                        },
                        new
                        {
                            BookID = 3,
                            AuthorID = 1
                        },
                        new
                        {
                            BookID = 4,
                            AuthorID = 9
                        },
                        new
                        {
                            BookID = 5,
                            AuthorID = 12
                        },
                        new
                        {
                            BookID = 6,
                            AuthorID = 11
                        },
                        new
                        {
                            BookID = 7,
                            AuthorID = 10
                        },
                        new
                        {
                            BookID = 8,
                            AuthorID = 6
                        },
                        new
                        {
                            BookID = 9,
                            AuthorID = 1
                        });
                });

            modelBuilder.Entity("DAL.Entities.ConnectionTables.BookCollectionBook", b =>
                {
                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("BookCollectionID")
                        .HasColumnType("int");

                    b.HasKey("BookID", "BookCollectionID");

                    b.HasIndex("BookCollectionID");

                    b.ToTable("BookCollection_Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            BookCollectionID = 1
                        },
                        new
                        {
                            BookID = 2,
                            BookCollectionID = 1
                        },
                        new
                        {
                            BookID = 3,
                            BookCollectionID = 1
                        });
                });

            modelBuilder.Entity("DAL.Entities.ConnectionTables.BookGenre", b =>
                {
                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.HasKey("GenreID", "BookID");

                    b.HasIndex("BookID");

                    b.ToTable("Book_Genres");

                    b.HasData(
                        new
                        {
                            GenreID = 7,
                            BookID = 1
                        },
                        new
                        {
                            GenreID = 7,
                            BookID = 2
                        },
                        new
                        {
                            GenreID = 7,
                            BookID = 3
                        },
                        new
                        {
                            GenreID = 1,
                            BookID = 4
                        },
                        new
                        {
                            GenreID = 2,
                            BookID = 5
                        },
                        new
                        {
                            GenreID = 3,
                            BookID = 6
                        },
                        new
                        {
                            GenreID = 2,
                            BookID = 7
                        },
                        new
                        {
                            GenreID = 5,
                            BookID = 8
                        },
                        new
                        {
                            GenreID = 7,
                            BookID = 9
                        });
                });

            modelBuilder.Entity("DAL.Entities.ConnectionTables.EBookEReaderInstance", b =>
                {
                    b.Property<int>("EBookID")
                        .HasColumnType("int");

                    b.Property<int>("EReaderInstanceID")
                        .HasColumnType("int");

                    b.HasKey("EBookID", "EReaderInstanceID");

                    b.HasIndex("EReaderInstanceID");

                    b.ToTable("EBookEReaderInstance");

                    b.HasData(
                        new
                        {
                            EBookID = 10,
                            EReaderInstanceID = 1
                        },
                        new
                        {
                            EBookID = 10,
                            EReaderInstanceID = 2
                        },
                        new
                        {
                            EBookID = 9,
                            EReaderInstanceID = 1
                        });
                });

            modelBuilder.Entity("DAL.Entities.ConnectionTables.ReservationBookInstance", b =>
                {
                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.Property<int>("BookInstanceID")
                        .HasColumnType("int");

                    b.HasKey("ReservationID", "BookInstanceID");

                    b.HasIndex("BookInstanceID");

                    b.ToTable("Reservation_BookInstances");

                    b.HasData(
                        new
                        {
                            ReservationID = 1,
                            BookInstanceID = 1
                        },
                        new
                        {
                            ReservationID = 2,
                            BookInstanceID = 2
                        },
                        new
                        {
                            ReservationID = 3,
                            BookInstanceID = 3
                        },
                        new
                        {
                            ReservationID = 4,
                            BookInstanceID = 1
                        },
                        new
                        {
                            ReservationID = 5,
                            BookInstanceID = 2
                        },
                        new
                        {
                            ReservationID = 6,
                            BookInstanceID = 5
                        },
                        new
                        {
                            ReservationID = 7,
                            BookInstanceID = 3
                        },
                        new
                        {
                            ReservationID = 8,
                            BookInstanceID = 7
                        },
                        new
                        {
                            ReservationID = 9,
                            BookInstanceID = 8
                        });
                });

            modelBuilder.Entity("DAL.Entities.EReader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyMake")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("MemoryInMB")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("EReaderTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyMake = "PocketBook",
                            MemoryInMB = 16000,
                            Model = "632 Touch HD 3"
                        },
                        new
                        {
                            Id = 2,
                            CompanyMake = "ONYX BOOX",
                            MemoryInMB = 32000,
                            Model = "Nova 3"
                        },
                        new
                        {
                            Id = 3,
                            CompanyMake = "PocketBook",
                            MemoryInMB = 32000,
                            Model = "1040 InkPad X"
                        });
                });

            modelBuilder.Entity("DAL.Entities.EReaderInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("EReaderTemplateID")
                        .HasColumnType("int");

                    b.Property<int>("EreaderOwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EReaderTemplateID");

                    b.HasIndex("EreaderOwnerId");

                    b.ToTable("EReaderInstances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EReaderTemplateID = 1,
                            EreaderOwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            EReaderTemplateID = 1,
                            EreaderOwnerId = 2
                        },
                        new
                        {
                            Id = 3,
                            EReaderTemplateID = 2,
                            EreaderOwnerId = 3
                        });
                });

            modelBuilder.Entity("DAL.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 7
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("DAL.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("Date");

                    b.Property<DateTime>("DateTill")
                        .HasColumnType("Date");

                    b.Property<int?>("EReaderID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EReaderID");

                    b.HasIndex("UserID");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateFrom = new DateTime(2021, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            DateFrom = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 1
                        },
                        new
                        {
                            Id = 3,
                            DateFrom = new DateTime(2021, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 1
                        },
                        new
                        {
                            Id = 4,
                            DateFrom = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 2
                        },
                        new
                        {
                            Id = 5,
                            DateFrom = new DateTime(2021, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 2
                        },
                        new
                        {
                            Id = 6,
                            DateFrom = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 4
                        },
                        new
                        {
                            Id = 7,
                            DateFrom = new DateTime(2021, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 3
                        },
                        new
                        {
                            Id = 8,
                            DateFrom = new DateTime(2021, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 2
                        },
                        new
                        {
                            Id = 9,
                            DateFrom = new DateTime(2021, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 1
                        },
                        new
                        {
                            Id = 10,
                            DateFrom = new DateTime(2021, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTill = new DateTime(2021, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EReaderID = 1,
                            UserID = 4
                        });
                });

            modelBuilder.Entity("DAL.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookTemplateID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("Date");

                    b.Property<int>("StarsAmmount")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookTemplateID");

                    b.HasIndex("UserID");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookTemplateID = 1,
                            Content = "Best",
                            CreationDate = new DateTime(2021, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StarsAmmount = 5,
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            BookTemplateID = 1,
                            Content = "Great!!",
                            CreationDate = new DateTime(2021, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StarsAmmount = 5,
                            UserID = 2
                        },
                        new
                        {
                            Id = 3,
                            BookTemplateID = 1,
                            Content = "huh",
                            CreationDate = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StarsAmmount = 1,
                            UserID = 3
                        },
                        new
                        {
                            Id = 4,
                            BookTemplateID = 8,
                            Content = "Changed my life",
                            CreationDate = new DateTime(2021, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StarsAmmount = 5,
                            UserID = 4
                        });
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HashedPassword")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Surname")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@gmail.com",
                            HashedPassword = "",
                            IsAdmin = true,
                            Name = "Alice",
                            Surname = "First"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@gmail.com",
                            HashedPassword = "",
                            IsAdmin = false,
                            Name = "Bob",
                            Surname = "Second"
                        },
                        new
                        {
                            Id = 3,
                            Email = "evee@gmail.com",
                            HashedPassword = "",
                            IsAdmin = false,
                            Name = "Eve",
                            Surname = "Third"
                        },
                        new
                        {
                            Id = 4,
                            Email = "jack@gmail.com",
                            HashedPassword = "",
                            IsAdmin = false,
                            Name = "Jack",
                            Surname = "Fourth"
                        },
                        new
                        {
                            Id = 5,
                            Email = "malory@gmail.com",
                            HashedPassword = "",
                            IsAdmin = false,
                            Name = "Malory",
                            Surname = "Fifth"
                        });
                });

            modelBuilder.Entity("DAL.Entities.EBook", b =>
                {
                    b.HasBaseType("DAL.Entities.Book");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<int>("MemorySize")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("EBook");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            DateOfRelease = new DateTime(1591, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shakespeare's immortal drama tells the story of star-crossed lovers, rival dynasties and bloody revenge. Romeo and Juliet is a hymn to youth and the thrill of forbidden love, charged with sexual passion and violence, but also a warning of death: a dazzling combination of bawdy comedy and high tragedy.",
                            ISBN = "9780141920252",
                            Language = 0,
                            PageCount = 320,
                            Title = "Romeo and Juliet",
                            Format = 0,
                            MemorySize = 1024
                        },
                        new
                        {
                            Id = 10,
                            DateOfRelease = new DateTime(1591, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "They dont like me at all :sadCatto: :(",
                            ISBN = "9780141920282",
                            Language = 0,
                            PageCount = 420,
                            Title = "Jacky and Katka against Speed",
                            Format = 0,
                            MemorySize = 1024
                        });
                });

            modelBuilder.Entity("DAL.Entities.BookCollection", b =>
                {
                    b.HasOne("DAL.Entities.User", "OwnerUser")
                        .WithMany("BookCollections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("DAL.Entities.BookInstance", b =>
                {
                    b.HasOne("DAL.Entities.User", "Owner")
                        .WithMany("MyBooks")
                        .HasForeignKey("BookOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Book", "FromBookTemplate")
                        .WithMany("BookInstances")
                        .HasForeignKey("BookTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromBookTemplate");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DAL.Entities.ConnectionTables.AuthorBook", b =>
                {
                    b.HasOne("DAL.Entities.Author", "Author")
                        .WithMany("AuthorsBooks")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Book", "Book")
                        .WithMany("Authors")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("DAL.Entities.ConnectionTables.BookCollectionBook", b =>
                {
                    b.HasOne("DAL.Entities.BookCollection", "BookCollect")
                        .WithMany("Books")
                        .HasForeignKey("BookCollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Book", "Book")
                        .WithMany("BookCollections")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BookCollect");
                });

            modelBuilder.Entity("DAL.Entities.ConnectionTables.BookGenre", b =>
                {
                    b.HasOne("DAL.Entities.Book", "Book")
                        .WithMany("Genres")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("DAL.Entities.ConnectionTables.EBookEReaderInstance", b =>
                {
                    b.HasOne("DAL.Entities.EBook", "EBook")
                        .WithMany("EReaders")
                        .HasForeignKey("EBookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.EReaderInstance", "EReaderInstance")
                        .WithMany("BooksIncluded")
                        .HasForeignKey("EReaderInstanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EBook");

                    b.Navigation("EReaderInstance");
                });

            modelBuilder.Entity("DAL.Entities.ConnectionTables.ReservationBookInstance", b =>
                {
                    b.HasOne("DAL.Entities.BookInstance", "BookInstance")
                        .WithMany("AllReservations")
                        .HasForeignKey("BookInstanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Reservation", "Reservation")
                        .WithMany("BookInstances")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookInstance");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("DAL.Entities.EReaderInstance", b =>
                {
                    b.HasOne("DAL.Entities.EReader", "EReaderTemplate")
                        .WithMany()
                        .HasForeignKey("EReaderTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.User", "Owner")
                        .WithMany("MyEReaders")
                        .HasForeignKey("EreaderOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EReaderTemplate");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DAL.Entities.Reservation", b =>
                {
                    b.HasOne("DAL.Entities.EReaderInstance", "EReader")
                        .WithMany("Reservations")
                        .HasForeignKey("EReaderID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EReader");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Review", b =>
                {
                    b.HasOne("DAL.Entities.Book", "ReservedBook")
                        .WithMany("Reviews")
                        .HasForeignKey("BookTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservedBook");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Author", b =>
                {
                    b.Navigation("AuthorsBooks");
                });

            modelBuilder.Entity("DAL.Entities.Book", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("BookCollections");

                    b.Navigation("BookInstances");

                    b.Navigation("Genres");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DAL.Entities.BookCollection", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Entities.BookInstance", b =>
                {
                    b.Navigation("AllReservations");
                });

            modelBuilder.Entity("DAL.Entities.EReaderInstance", b =>
                {
                    b.Navigation("BooksIncluded");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DAL.Entities.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Entities.Reservation", b =>
                {
                    b.Navigation("BookInstances");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Navigation("BookCollections");

                    b.Navigation("MyBooks");

                    b.Navigation("MyEReaders");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DAL.Entities.EBook", b =>
                {
                    b.Navigation("EReaders");
                });
#pragma warning restore 612, 618
        }
    }
}
